spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/notesdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USER:notes}
    password: ${DB_PASSWORD:notes123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.notes.api: DEBUG
